version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "gradle"
    directory: "/gradle/libs.versions.toml"
    schedule:
      interval: "weekly"
